/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as ApiBidsRouteImport } from './routes/api/bids'
import { Route as ApiClientsRouteImport } from './routes/api/clients'
import { Route as ApiInvoicesRouteImport } from './routes/api/invoices'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiMeetingsRouteImport } from './routes/api/meetings'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as Vs5blocVsFieldwireRouteImport } from './routes/vs/5bloc-vs-fieldwire'
import { Route as Vs5blocVsProcoreRouteImport } from './routes/vs/5bloc-vs-procore'
import { Route as AuthenticatedAppClientsRouteImport } from './routes/_authenticated/_app/clients'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/_app/documents'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/_app/projects'
import { Route as ApiClientsIdRouteImport } from './routes/api/clients/$id'
import { Route as ApiFilesUploadRouteImport } from './routes/api/files/upload'
import { Route as ApiOrgStudioProjectRouteImport } from './routes/api/org/studio-project'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as AuthenticatedAppClientsIdRouteImport } from './routes/_authenticated/_app/clients/$id'
import { Route as AuthenticatedAppProjectsNewRouteImport } from './routes/_authenticated/_app/projects/new'
import { Route as ApiProjectsIdDocumentsRouteImport } from './routes/api/projects/$id/documents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBidsRoute = ApiBidsRouteImport.update({
  id: '/api/bids',
  path: '/api/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsRoute = ApiClientsRouteImport.update({
  id: '/api/clients',
  path: '/api/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesRoute = ApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsRoute = ApiMeetingsRouteImport.update({
  id: '/api/meetings',
  path: '/api/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const Vs5blocVsFieldwireRoute = Vs5blocVsFieldwireRouteImport.update({
  id: '/vs/5bloc-vs-fieldwire',
  path: '/vs/5bloc-vs-fieldwire',
  getParentRoute: () => rootRouteImport,
} as any)
const Vs5blocVsProcoreRoute = Vs5blocVsProcoreRouteImport.update({
  id: '/vs/5bloc-vs-procore',
  path: '/vs/5bloc-vs-procore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppClientsRoute = AuthenticatedAppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const ApiClientsIdRoute = ApiClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiClientsRoute,
} as any)
const ApiFilesUploadRoute = ApiFilesUploadRouteImport.update({
  id: '/api/files/upload',
  path: '/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgStudioProjectRoute = ApiOrgStudioProjectRouteImport.update({
  id: '/api/org/studio-project',
  path: '/api/org/studio-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const AuthenticatedAppClientsIdRoute =
  AuthenticatedAppClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppClientsRoute,
  } as any)
const AuthenticatedAppProjectsNewRoute =
  AuthenticatedAppProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const ApiProjectsIdDocumentsRoute = ApiProjectsIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/bids': typeof ApiBidsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRoute
  '/api/me': typeof ApiMeRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/vs/5bloc-vs-fieldwire': typeof Vs5blocVsFieldwireRoute
  '/vs/5bloc-vs-procore': typeof Vs5blocVsProcoreRoute
  '/clients': typeof AuthenticatedAppClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/documents': typeof AuthenticatedAppDocumentsRoute
  '/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/org/studio-project': typeof ApiOrgStudioProjectRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/clients/$id': typeof AuthenticatedAppClientsIdRoute
  '/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/projects/$id/documents': typeof ApiProjectsIdDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/bids': typeof ApiBidsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRoute
  '/api/me': typeof ApiMeRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/vs/5bloc-vs-fieldwire': typeof Vs5blocVsFieldwireRoute
  '/vs/5bloc-vs-procore': typeof Vs5blocVsProcoreRoute
  '/clients': typeof AuthenticatedAppClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/documents': typeof AuthenticatedAppDocumentsRoute
  '/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/org/studio-project': typeof ApiOrgStudioProjectRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/clients/$id': typeof AuthenticatedAppClientsIdRoute
  '/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/projects/$id/documents': typeof ApiProjectsIdDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/api/activity': typeof ApiActivityRoute
  '/api/bids': typeof ApiBidsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRoute
  '/api/me': typeof ApiMeRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/vs/5bloc-vs-fieldwire': typeof Vs5blocVsFieldwireRoute
  '/vs/5bloc-vs-procore': typeof Vs5blocVsProcoreRoute
  '/_authenticated/_app/clients': typeof AuthenticatedAppClientsRouteWithChildren
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/_app/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/org/studio-project': typeof ApiOrgStudioProjectRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/_authenticated/_app/clients/$id': typeof AuthenticatedAppClientsIdRoute
  '/_authenticated/_app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/projects/$id/documents': typeof ApiProjectsIdDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/changelog'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/api/activity'
    | '/api/bids'
    | '/api/clients'
    | '/api/invoices'
    | '/api/me'
    | '/api/meetings'
    | '/api/projects'
    | '/auth/callback'
    | '/vs/5bloc-vs-fieldwire'
    | '/vs/5bloc-vs-procore'
    | '/clients'
    | '/dashboard'
    | '/documents'
    | '/projects'
    | '/api/clients/$id'
    | '/api/files/upload'
    | '/api/org/studio-project'
    | '/api/projects/$id'
    | '/clients/$id'
    | '/projects/new'
    | '/api/projects/$id/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/api/activity'
    | '/api/bids'
    | '/api/clients'
    | '/api/invoices'
    | '/api/me'
    | '/api/meetings'
    | '/api/projects'
    | '/auth/callback'
    | '/vs/5bloc-vs-fieldwire'
    | '/vs/5bloc-vs-procore'
    | '/clients'
    | '/dashboard'
    | '/documents'
    | '/projects'
    | '/api/clients/$id'
    | '/api/files/upload'
    | '/api/org/studio-project'
    | '/api/projects/$id'
    | '/clients/$id'
    | '/projects/new'
    | '/api/projects/$id/documents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/changelog'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_authenticated/_app'
    | '/api/activity'
    | '/api/bids'
    | '/api/clients'
    | '/api/invoices'
    | '/api/me'
    | '/api/meetings'
    | '/api/projects'
    | '/auth/callback'
    | '/vs/5bloc-vs-fieldwire'
    | '/vs/5bloc-vs-procore'
    | '/_authenticated/_app/clients'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/documents'
    | '/_authenticated/_app/projects'
    | '/api/clients/$id'
    | '/api/files/upload'
    | '/api/org/studio-project'
    | '/api/projects/$id'
    | '/_authenticated/_app/clients/$id'
    | '/_authenticated/_app/projects/new'
    | '/api/projects/$id/documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ChangelogRoute: typeof ChangelogRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiActivityRoute: typeof ApiActivityRoute
  ApiBidsRoute: typeof ApiBidsRoute
  ApiClientsRoute: typeof ApiClientsRouteWithChildren
  ApiInvoicesRoute: typeof ApiInvoicesRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiMeetingsRoute: typeof ApiMeetingsRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  Vs5blocVsFieldwireRoute: typeof Vs5blocVsFieldwireRoute
  Vs5blocVsProcoreRoute: typeof Vs5blocVsProcoreRoute
  ApiFilesUploadRoute: typeof ApiFilesUploadRoute
  ApiOrgStudioProjectRoute: typeof ApiOrgStudioProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bids': {
      id: '/api/bids'
      path: '/api/bids'
      fullPath: '/api/bids'
      preLoaderRoute: typeof ApiBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients': {
      id: '/api/clients'
      path: '/api/clients'
      fullPath: '/api/clients'
      preLoaderRoute: typeof ApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices': {
      id: '/api/invoices'
      path: '/api/invoices'
      fullPath: '/api/invoices'
      preLoaderRoute: typeof ApiInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings': {
      id: '/api/meetings'
      path: '/api/meetings'
      fullPath: '/api/meetings'
      preLoaderRoute: typeof ApiMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/5bloc-vs-fieldwire': {
      id: '/vs/5bloc-vs-fieldwire'
      path: '/vs/5bloc-vs-fieldwire'
      fullPath: '/vs/5bloc-vs-fieldwire'
      preLoaderRoute: typeof Vs5blocVsFieldwireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/5bloc-vs-procore': {
      id: '/vs/5bloc-vs-procore'
      path: '/vs/5bloc-vs-procore'
      fullPath: '/vs/5bloc-vs-procore'
      preLoaderRoute: typeof Vs5blocVsProcoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/clients': {
      id: '/_authenticated/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedAppClientsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/documents': {
      id: '/_authenticated/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects': {
      id: '/_authenticated/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/clients/$id': {
      id: '/api/clients/$id'
      path: '/$id'
      fullPath: '/api/clients/$id'
      preLoaderRoute: typeof ApiClientsIdRouteImport
      parentRoute: typeof ApiClientsRoute
    }
    '/api/files/upload': {
      id: '/api/files/upload'
      path: '/api/files/upload'
      fullPath: '/api/files/upload'
      preLoaderRoute: typeof ApiFilesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/studio-project': {
      id: '/api/org/studio-project'
      path: '/api/org/studio-project'
      fullPath: '/api/org/studio-project'
      preLoaderRoute: typeof ApiOrgStudioProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/_authenticated/_app/clients/$id': {
      id: '/_authenticated/_app/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedAppClientsIdRouteImport
      parentRoute: typeof AuthenticatedAppClientsRoute
    }
    '/_authenticated/_app/projects/new': {
      id: '/_authenticated/_app/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedAppProjectsNewRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/api/projects/$id/documents': {
      id: '/api/projects/$id/documents'
      path: '/documents'
      fullPath: '/api/projects/$id/documents'
      preLoaderRoute: typeof ApiProjectsIdDocumentsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
  }
}

interface AuthenticatedAppClientsRouteChildren {
  AuthenticatedAppClientsIdRoute: typeof AuthenticatedAppClientsIdRoute
}

const AuthenticatedAppClientsRouteChildren: AuthenticatedAppClientsRouteChildren =
  {
    AuthenticatedAppClientsIdRoute: AuthenticatedAppClientsIdRoute,
  }

const AuthenticatedAppClientsRouteWithChildren =
  AuthenticatedAppClientsRoute._addFileChildren(
    AuthenticatedAppClientsRouteChildren,
  )

interface AuthenticatedAppProjectsRouteChildren {
  AuthenticatedAppProjectsNewRoute: typeof AuthenticatedAppProjectsNewRoute
}

const AuthenticatedAppProjectsRouteChildren: AuthenticatedAppProjectsRouteChildren =
  {
    AuthenticatedAppProjectsNewRoute: AuthenticatedAppProjectsNewRoute,
  }

const AuthenticatedAppProjectsRouteWithChildren =
  AuthenticatedAppProjectsRoute._addFileChildren(
    AuthenticatedAppProjectsRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppClientsRoute: typeof AuthenticatedAppClientsRouteWithChildren
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRouteWithChildren
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppClientsRoute: AuthenticatedAppClientsRouteWithChildren,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRouteWithChildren,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiClientsRouteChildren {
  ApiClientsIdRoute: typeof ApiClientsIdRoute
}

const ApiClientsRouteChildren: ApiClientsRouteChildren = {
  ApiClientsIdRoute: ApiClientsIdRoute,
}

const ApiClientsRouteWithChildren = ApiClientsRoute._addFileChildren(
  ApiClientsRouteChildren,
)

interface ApiProjectsIdRouteChildren {
  ApiProjectsIdDocumentsRoute: typeof ApiProjectsIdDocumentsRoute
}

const ApiProjectsIdRouteChildren: ApiProjectsIdRouteChildren = {
  ApiProjectsIdDocumentsRoute: ApiProjectsIdDocumentsRoute,
}

const ApiProjectsIdRouteWithChildren = ApiProjectsIdRoute._addFileChildren(
  ApiProjectsIdRouteChildren,
)

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRouteWithChildren
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRouteWithChildren,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiActivityRoute: ApiActivityRoute,
  ApiBidsRoute: ApiBidsRoute,
  ApiClientsRoute: ApiClientsRouteWithChildren,
  ApiInvoicesRoute: ApiInvoicesRoute,
  ApiMeRoute: ApiMeRoute,
  ApiMeetingsRoute: ApiMeetingsRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  Vs5blocVsFieldwireRoute: Vs5blocVsFieldwireRoute,
  Vs5blocVsProcoreRoute: Vs5blocVsProcoreRoute,
  ApiFilesUploadRoute: ApiFilesUploadRoute,
  ApiOrgStudioProjectRoute: ApiOrgStudioProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
