/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as ApiBidsRouteImport } from './routes/api/bids'
import { Route as ApiClientsRouteImport } from './routes/api/clients'
import { Route as ApiContractorsRouteImport } from './routes/api/contractors'
import { Route as ApiInvitesRouteImport } from './routes/api/invites'
import { Route as ApiInvoicesRouteImport } from './routes/api/invoices'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiMeetingsRouteImport } from './routes/api/meetings'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiTendersRouteImport } from './routes/api/tenders'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as Vs5blocVsFieldwireRouteImport } from './routes/vs/5bloc-vs-fieldwire'
import { Route as Vs5blocVsProcoreRouteImport } from './routes/vs/5bloc-vs-procore'
import { Route as AuthenticatedAppCadRouteImport } from './routes/_authenticated/_app/cad'
import { Route as AuthenticatedAppCalendarRouteImport } from './routes/_authenticated/_app/calendar'
import { Route as AuthenticatedAppCatalogRouteImport } from './routes/_authenticated/_app/catalog'
import { Route as AuthenticatedAppCoordinationRouteImport } from './routes/_authenticated/_app/coordination'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/_app/documents'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/_app/integrations'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/_app/messages'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as ApiClientsIdRouteImport } from './routes/api/clients/$id'
import { Route as ApiContractorsIdRouteImport } from './routes/api/contractors/$id'
import { Route as ApiContractorsArchitectsRouteImport } from './routes/api/contractors/architects'
import { Route as ApiFilesDownloadRouteImport } from './routes/api/files/download'
import { Route as ApiFilesUploadRouteImport } from './routes/api/files/upload'
import { Route as ApiInvoicesIdRouteImport } from './routes/api/invoices/$id'
import { Route as ApiMessagesConversationsRouteImport } from './routes/api/messages/conversations'
import { Route as ApiOrgStudioProjectRouteImport } from './routes/api/org/studio-project'
import { Route as ApiOrgTeamRouteImport } from './routes/api/org/team'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as ApiTendersIdRouteImport } from './routes/api/tenders/$id'
import { Route as AuthenticatedAppClientsIndexRouteImport } from './routes/_authenticated/_app/clients/index'
import { Route as AuthenticatedAppClientsIdRouteImport } from './routes/_authenticated/_app/clients/$id'
import { Route as AuthenticatedAppInvoicesIndexRouteImport } from './routes/_authenticated/_app/invoices/index'
import { Route as AuthenticatedAppInvoicesNewRouteImport } from './routes/_authenticated/_app/invoices/new'
import { Route as AuthenticatedAppMarketplaceIndexRouteImport } from './routes/_authenticated/_app/marketplace/index'
import { Route as AuthenticatedAppMarketplaceIdRouteImport } from './routes/_authenticated/_app/marketplace/$id'
import { Route as AuthenticatedAppProjectsIndexRouteImport } from './routes/_authenticated/_app/projects/index'
import { Route as AuthenticatedAppProjectsNewRouteImport } from './routes/_authenticated/_app/projects/new'
import { Route as ApiContractorsArchitectsIdRouteImport } from './routes/api/contractors/architects/$id'
import { Route as ApiMessagesUsersSearchRouteImport } from './routes/api/messages/users/search'
import { Route as ApiProjectsIdConsultantPaymentsRouteImport } from './routes/api/projects/$id/consultant-payments'
import { Route as ApiProjectsIdDocumentAnnotationsRouteImport } from './routes/api/projects/$id/document-annotations'
import { Route as ApiProjectsIdDocumentVersionsRouteImport } from './routes/api/projects/$id/document-versions'
import { Route as ApiProjectsIdDocumentsRouteImport } from './routes/api/projects/$id/documents'
import { Route as ApiProjectsIdExpensesRouteImport } from './routes/api/projects/$id/expenses'
import { Route as ApiProjectsIdIssuesRouteImport } from './routes/api/projects/$id/issues'
import { Route as ApiProjectsIdMeetingsRouteImport } from './routes/api/projects/$id/meetings'
import { Route as ApiProjectsIdMembersRouteImport } from './routes/api/projects/$id/members'
import { Route as ApiProjectsIdMessagesRouteImport } from './routes/api/projects/$id/messages'
import { Route as ApiProjectsIdMilestonesRouteImport } from './routes/api/projects/$id/milestones'
import { Route as ApiProjectsIdPermitsRouteImport } from './routes/api/projects/$id/permits'
import { Route as ApiProjectsIdRfisRouteImport } from './routes/api/projects/$id/rfis'
import { Route as ApiProjectsIdSiteRouteImport } from './routes/api/projects/$id/site'
import { Route as ApiProjectsIdSubmittalsRouteImport } from './routes/api/projects/$id/submittals'
import { Route as ApiProjectsIdTendersRouteImport } from './routes/api/projects/$id/tenders'
import { Route as ApiProjectsIdTransmittalsRouteImport } from './routes/api/projects/$id/transmittals'
import { Route as AuthenticatedAppMarketplaceArchitectsIdRouteImport } from './routes/_authenticated/_app/marketplace/architects/$id'
import { Route as AuthenticatedAppMarketplaceTendersIdRouteImport } from './routes/_authenticated/_app/marketplace/tenders/$id'
import { Route as AuthenticatedAppProjectsIdIndexRouteImport } from './routes/_authenticated/_app/projects/$id/index'
import { Route as AuthenticatedAppProjectsIdDocumentsRouteImport } from './routes/_authenticated/_app/projects/$id/documents'
import { Route as AuthenticatedAppProjectsIdInvoicesRouteImport } from './routes/_authenticated/_app/projects/$id/invoices'
import { Route as AuthenticatedAppProjectsIdIssuesRouteImport } from './routes/_authenticated/_app/projects/$id/issues'
import { Route as AuthenticatedAppProjectsIdMeetingsRouteImport } from './routes/_authenticated/_app/projects/$id/meetings'
import { Route as AuthenticatedAppProjectsIdMessagesRouteImport } from './routes/_authenticated/_app/projects/$id/messages'
import { Route as AuthenticatedAppProjectsIdPermitsRouteImport } from './routes/_authenticated/_app/projects/$id/permits'
import { Route as AuthenticatedAppProjectsIdPortalRouteImport } from './routes/_authenticated/_app/projects/$id/portal'
import { Route as AuthenticatedAppProjectsIdRfisRouteImport } from './routes/_authenticated/_app/projects/$id/rfis'
import { Route as AuthenticatedAppProjectsIdSettingsRouteImport } from './routes/_authenticated/_app/projects/$id/settings'
import { Route as AuthenticatedAppProjectsIdSiteRouteImport } from './routes/_authenticated/_app/projects/$id/site'
import { Route as AuthenticatedAppProjectsIdSubmittalsRouteImport } from './routes/_authenticated/_app/projects/$id/submittals'
import { Route as AuthenticatedAppProjectsIdTeamRouteImport } from './routes/_authenticated/_app/projects/$id/team'
import { Route as AuthenticatedAppProjectsIdTransmittalsRouteImport } from './routes/_authenticated/_app/projects/$id/transmittals'
import { Route as ApiMessagesConversationsIdMembersRouteImport } from './routes/api/messages/conversations/$id/members'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBidsRoute = ApiBidsRouteImport.update({
  id: '/api/bids',
  path: '/api/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsRoute = ApiClientsRouteImport.update({
  id: '/api/clients',
  path: '/api/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContractorsRoute = ApiContractorsRouteImport.update({
  id: '/api/contractors',
  path: '/api/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitesRoute = ApiInvitesRouteImport.update({
  id: '/api/invites',
  path: '/api/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesRoute = ApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsRoute = ApiMeetingsRouteImport.update({
  id: '/api/meetings',
  path: '/api/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTendersRoute = ApiTendersRouteImport.update({
  id: '/api/tenders',
  path: '/api/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const Vs5blocVsFieldwireRoute = Vs5blocVsFieldwireRouteImport.update({
  id: '/vs/5bloc-vs-fieldwire',
  path: '/vs/5bloc-vs-fieldwire',
  getParentRoute: () => rootRouteImport,
} as any)
const Vs5blocVsProcoreRoute = Vs5blocVsProcoreRouteImport.update({
  id: '/vs/5bloc-vs-procore',
  path: '/vs/5bloc-vs-procore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppCadRoute = AuthenticatedAppCadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCalendarRoute =
  AuthenticatedAppCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCatalogRoute = AuthenticatedAppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCoordinationRoute =
  AuthenticatedAppCoordinationRouteImport.update({
    id: '/coordination',
    path: '/coordination',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const ApiClientsIdRoute = ApiClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiClientsRoute,
} as any)
const ApiContractorsIdRoute = ApiContractorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiContractorsRoute,
} as any)
const ApiContractorsArchitectsRoute =
  ApiContractorsArchitectsRouteImport.update({
    id: '/architects',
    path: '/architects',
    getParentRoute: () => ApiContractorsRoute,
  } as any)
const ApiFilesDownloadRoute = ApiFilesDownloadRouteImport.update({
  id: '/api/files/download',
  path: '/api/files/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesUploadRoute = ApiFilesUploadRouteImport.update({
  id: '/api/files/upload',
  path: '/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesIdRoute = ApiInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvoicesRoute,
} as any)
const ApiMessagesConversationsRoute =
  ApiMessagesConversationsRouteImport.update({
    id: '/api/messages/conversations',
    path: '/api/messages/conversations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgStudioProjectRoute = ApiOrgStudioProjectRouteImport.update({
  id: '/api/org/studio-project',
  path: '/api/org/studio-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgTeamRoute = ApiOrgTeamRouteImport.update({
  id: '/api/org/team',
  path: '/api/org/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiTendersIdRoute = ApiTendersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTendersRoute,
} as any)
const AuthenticatedAppClientsIndexRoute =
  AuthenticatedAppClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppClientsIdRoute =
  AuthenticatedAppClientsIdRouteImport.update({
    id: '/clients/$id',
    path: '/clients/$id',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppInvoicesIndexRoute =
  AuthenticatedAppInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppInvoicesNewRoute =
  AuthenticatedAppInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMarketplaceIndexRoute =
  AuthenticatedAppMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMarketplaceIdRoute =
  AuthenticatedAppMarketplaceIdRouteImport.update({
    id: '/marketplace/$id',
    path: '/marketplace/$id',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIndexRoute =
  AuthenticatedAppProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsNewRoute =
  AuthenticatedAppProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const ApiContractorsArchitectsIdRoute =
  ApiContractorsArchitectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiContractorsArchitectsRoute,
  } as any)
const ApiMessagesUsersSearchRoute = ApiMessagesUsersSearchRouteImport.update({
  id: '/api/messages/users/search',
  path: '/api/messages/users/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdConsultantPaymentsRoute =
  ApiProjectsIdConsultantPaymentsRouteImport.update({
    id: '/consultant-payments',
    path: '/consultant-payments',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const ApiProjectsIdDocumentAnnotationsRoute =
  ApiProjectsIdDocumentAnnotationsRouteImport.update({
    id: '/document-annotations',
    path: '/document-annotations',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const ApiProjectsIdDocumentVersionsRoute =
  ApiProjectsIdDocumentVersionsRouteImport.update({
    id: '/document-versions',
    path: '/document-versions',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const ApiProjectsIdDocumentsRoute = ApiProjectsIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdExpensesRoute = ApiProjectsIdExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdIssuesRoute = ApiProjectsIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdMeetingsRoute = ApiProjectsIdMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdMembersRoute = ApiProjectsIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdMessagesRoute = ApiProjectsIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdMilestonesRoute = ApiProjectsIdMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdPermitsRoute = ApiProjectsIdPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdRfisRoute = ApiProjectsIdRfisRouteImport.update({
  id: '/rfis',
  path: '/rfis',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdSiteRoute = ApiProjectsIdSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdSubmittalsRoute = ApiProjectsIdSubmittalsRouteImport.update({
  id: '/submittals',
  path: '/submittals',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdTendersRoute = ApiProjectsIdTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdTransmittalsRoute =
  ApiProjectsIdTransmittalsRouteImport.update({
    id: '/transmittals',
    path: '/transmittals',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const AuthenticatedAppMarketplaceArchitectsIdRoute =
  AuthenticatedAppMarketplaceArchitectsIdRouteImport.update({
    id: '/marketplace/architects/$id',
    path: '/marketplace/architects/$id',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMarketplaceTendersIdRoute =
  AuthenticatedAppMarketplaceTendersIdRouteImport.update({
    id: '/marketplace/tenders/$id',
    path: '/marketplace/tenders/$id',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdIndexRoute =
  AuthenticatedAppProjectsIdIndexRouteImport.update({
    id: '/projects/$id/',
    path: '/projects/$id/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdDocumentsRoute =
  AuthenticatedAppProjectsIdDocumentsRouteImport.update({
    id: '/projects/$id/documents',
    path: '/projects/$id/documents',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdInvoicesRoute =
  AuthenticatedAppProjectsIdInvoicesRouteImport.update({
    id: '/projects/$id/invoices',
    path: '/projects/$id/invoices',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdIssuesRoute =
  AuthenticatedAppProjectsIdIssuesRouteImport.update({
    id: '/projects/$id/issues',
    path: '/projects/$id/issues',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdMeetingsRoute =
  AuthenticatedAppProjectsIdMeetingsRouteImport.update({
    id: '/projects/$id/meetings',
    path: '/projects/$id/meetings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdMessagesRoute =
  AuthenticatedAppProjectsIdMessagesRouteImport.update({
    id: '/projects/$id/messages',
    path: '/projects/$id/messages',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdPermitsRoute =
  AuthenticatedAppProjectsIdPermitsRouteImport.update({
    id: '/projects/$id/permits',
    path: '/projects/$id/permits',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdPortalRoute =
  AuthenticatedAppProjectsIdPortalRouteImport.update({
    id: '/projects/$id/portal',
    path: '/projects/$id/portal',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdRfisRoute =
  AuthenticatedAppProjectsIdRfisRouteImport.update({
    id: '/projects/$id/rfis',
    path: '/projects/$id/rfis',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdSettingsRoute =
  AuthenticatedAppProjectsIdSettingsRouteImport.update({
    id: '/projects/$id/settings',
    path: '/projects/$id/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdSiteRoute =
  AuthenticatedAppProjectsIdSiteRouteImport.update({
    id: '/projects/$id/site',
    path: '/projects/$id/site',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdSubmittalsRoute =
  AuthenticatedAppProjectsIdSubmittalsRouteImport.update({
    id: '/projects/$id/submittals',
    path: '/projects/$id/submittals',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdTeamRoute =
  AuthenticatedAppProjectsIdTeamRouteImport.update({
    id: '/projects/$id/team',
    path: '/projects/$id/team',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdTransmittalsRoute =
  AuthenticatedAppProjectsIdTransmittalsRouteImport.update({
    id: '/projects/$id/transmittals',
    path: '/projects/$id/transmittals',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const ApiMessagesConversationsIdMembersRoute =
  ApiMessagesConversationsIdMembersRouteImport.update({
    id: '/$id/members',
    path: '/$id/members',
    getParentRoute: () => ApiMessagesConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/bids': typeof ApiBidsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/contractors': typeof ApiContractorsRouteWithChildren
  '/api/invites': typeof ApiInvitesRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/tenders': typeof ApiTendersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/vs/5bloc-vs-fieldwire': typeof Vs5blocVsFieldwireRoute
  '/vs/5bloc-vs-procore': typeof Vs5blocVsProcoreRoute
  '/cad': typeof AuthenticatedAppCadRoute
  '/calendar': typeof AuthenticatedAppCalendarRoute
  '/catalog': typeof AuthenticatedAppCatalogRoute
  '/coordination': typeof AuthenticatedAppCoordinationRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/documents': typeof AuthenticatedAppDocumentsRoute
  '/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/messages': typeof AuthenticatedAppMessagesRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/contractors/$id': typeof ApiContractorsIdRoute
  '/api/contractors/architects': typeof ApiContractorsArchitectsRouteWithChildren
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRouteWithChildren
  '/api/org/studio-project': typeof ApiOrgStudioProjectRoute
  '/api/org/team': typeof ApiOrgTeamRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/tenders/$id': typeof ApiTendersIdRoute
  '/clients/$id': typeof AuthenticatedAppClientsIdRoute
  '/invoices/new': typeof AuthenticatedAppInvoicesNewRoute
  '/marketplace/$id': typeof AuthenticatedAppMarketplaceIdRoute
  '/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/contractors/architects/$id': typeof ApiContractorsArchitectsIdRoute
  '/api/messages/users/search': typeof ApiMessagesUsersSearchRoute
  '/api/projects/$id/consultant-payments': typeof ApiProjectsIdConsultantPaymentsRoute
  '/api/projects/$id/document-annotations': typeof ApiProjectsIdDocumentAnnotationsRoute
  '/api/projects/$id/document-versions': typeof ApiProjectsIdDocumentVersionsRoute
  '/api/projects/$id/documents': typeof ApiProjectsIdDocumentsRoute
  '/api/projects/$id/expenses': typeof ApiProjectsIdExpensesRoute
  '/api/projects/$id/issues': typeof ApiProjectsIdIssuesRoute
  '/api/projects/$id/meetings': typeof ApiProjectsIdMeetingsRoute
  '/api/projects/$id/members': typeof ApiProjectsIdMembersRoute
  '/api/projects/$id/messages': typeof ApiProjectsIdMessagesRoute
  '/api/projects/$id/milestones': typeof ApiProjectsIdMilestonesRoute
  '/api/projects/$id/permits': typeof ApiProjectsIdPermitsRoute
  '/api/projects/$id/rfis': typeof ApiProjectsIdRfisRoute
  '/api/projects/$id/site': typeof ApiProjectsIdSiteRoute
  '/api/projects/$id/submittals': typeof ApiProjectsIdSubmittalsRoute
  '/api/projects/$id/tenders': typeof ApiProjectsIdTendersRoute
  '/api/projects/$id/transmittals': typeof ApiProjectsIdTransmittalsRoute
  '/clients/': typeof AuthenticatedAppClientsIndexRoute
  '/invoices/': typeof AuthenticatedAppInvoicesIndexRoute
  '/marketplace/': typeof AuthenticatedAppMarketplaceIndexRoute
  '/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/marketplace/architects/$id': typeof AuthenticatedAppMarketplaceArchitectsIdRoute
  '/marketplace/tenders/$id': typeof AuthenticatedAppMarketplaceTendersIdRoute
  '/projects/$id/documents': typeof AuthenticatedAppProjectsIdDocumentsRoute
  '/projects/$id/invoices': typeof AuthenticatedAppProjectsIdInvoicesRoute
  '/projects/$id/issues': typeof AuthenticatedAppProjectsIdIssuesRoute
  '/projects/$id/meetings': typeof AuthenticatedAppProjectsIdMeetingsRoute
  '/projects/$id/messages': typeof AuthenticatedAppProjectsIdMessagesRoute
  '/projects/$id/permits': typeof AuthenticatedAppProjectsIdPermitsRoute
  '/projects/$id/portal': typeof AuthenticatedAppProjectsIdPortalRoute
  '/projects/$id/rfis': typeof AuthenticatedAppProjectsIdRfisRoute
  '/projects/$id/settings': typeof AuthenticatedAppProjectsIdSettingsRoute
  '/projects/$id/site': typeof AuthenticatedAppProjectsIdSiteRoute
  '/projects/$id/submittals': typeof AuthenticatedAppProjectsIdSubmittalsRoute
  '/projects/$id/team': typeof AuthenticatedAppProjectsIdTeamRoute
  '/projects/$id/transmittals': typeof AuthenticatedAppProjectsIdTransmittalsRoute
  '/api/messages/conversations/$id/members': typeof ApiMessagesConversationsIdMembersRoute
  '/projects/$id/': typeof AuthenticatedAppProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/bids': typeof ApiBidsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/contractors': typeof ApiContractorsRouteWithChildren
  '/api/invites': typeof ApiInvitesRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/tenders': typeof ApiTendersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/vs/5bloc-vs-fieldwire': typeof Vs5blocVsFieldwireRoute
  '/vs/5bloc-vs-procore': typeof Vs5blocVsProcoreRoute
  '/cad': typeof AuthenticatedAppCadRoute
  '/calendar': typeof AuthenticatedAppCalendarRoute
  '/catalog': typeof AuthenticatedAppCatalogRoute
  '/coordination': typeof AuthenticatedAppCoordinationRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/documents': typeof AuthenticatedAppDocumentsRoute
  '/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/messages': typeof AuthenticatedAppMessagesRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/contractors/$id': typeof ApiContractorsIdRoute
  '/api/contractors/architects': typeof ApiContractorsArchitectsRouteWithChildren
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRouteWithChildren
  '/api/org/studio-project': typeof ApiOrgStudioProjectRoute
  '/api/org/team': typeof ApiOrgTeamRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/tenders/$id': typeof ApiTendersIdRoute
  '/clients/$id': typeof AuthenticatedAppClientsIdRoute
  '/invoices/new': typeof AuthenticatedAppInvoicesNewRoute
  '/marketplace/$id': typeof AuthenticatedAppMarketplaceIdRoute
  '/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/contractors/architects/$id': typeof ApiContractorsArchitectsIdRoute
  '/api/messages/users/search': typeof ApiMessagesUsersSearchRoute
  '/api/projects/$id/consultant-payments': typeof ApiProjectsIdConsultantPaymentsRoute
  '/api/projects/$id/document-annotations': typeof ApiProjectsIdDocumentAnnotationsRoute
  '/api/projects/$id/document-versions': typeof ApiProjectsIdDocumentVersionsRoute
  '/api/projects/$id/documents': typeof ApiProjectsIdDocumentsRoute
  '/api/projects/$id/expenses': typeof ApiProjectsIdExpensesRoute
  '/api/projects/$id/issues': typeof ApiProjectsIdIssuesRoute
  '/api/projects/$id/meetings': typeof ApiProjectsIdMeetingsRoute
  '/api/projects/$id/members': typeof ApiProjectsIdMembersRoute
  '/api/projects/$id/messages': typeof ApiProjectsIdMessagesRoute
  '/api/projects/$id/milestones': typeof ApiProjectsIdMilestonesRoute
  '/api/projects/$id/permits': typeof ApiProjectsIdPermitsRoute
  '/api/projects/$id/rfis': typeof ApiProjectsIdRfisRoute
  '/api/projects/$id/site': typeof ApiProjectsIdSiteRoute
  '/api/projects/$id/submittals': typeof ApiProjectsIdSubmittalsRoute
  '/api/projects/$id/tenders': typeof ApiProjectsIdTendersRoute
  '/api/projects/$id/transmittals': typeof ApiProjectsIdTransmittalsRoute
  '/clients': typeof AuthenticatedAppClientsIndexRoute
  '/invoices': typeof AuthenticatedAppInvoicesIndexRoute
  '/marketplace': typeof AuthenticatedAppMarketplaceIndexRoute
  '/projects': typeof AuthenticatedAppProjectsIndexRoute
  '/marketplace/architects/$id': typeof AuthenticatedAppMarketplaceArchitectsIdRoute
  '/marketplace/tenders/$id': typeof AuthenticatedAppMarketplaceTendersIdRoute
  '/projects/$id/documents': typeof AuthenticatedAppProjectsIdDocumentsRoute
  '/projects/$id/invoices': typeof AuthenticatedAppProjectsIdInvoicesRoute
  '/projects/$id/issues': typeof AuthenticatedAppProjectsIdIssuesRoute
  '/projects/$id/meetings': typeof AuthenticatedAppProjectsIdMeetingsRoute
  '/projects/$id/messages': typeof AuthenticatedAppProjectsIdMessagesRoute
  '/projects/$id/permits': typeof AuthenticatedAppProjectsIdPermitsRoute
  '/projects/$id/portal': typeof AuthenticatedAppProjectsIdPortalRoute
  '/projects/$id/rfis': typeof AuthenticatedAppProjectsIdRfisRoute
  '/projects/$id/settings': typeof AuthenticatedAppProjectsIdSettingsRoute
  '/projects/$id/site': typeof AuthenticatedAppProjectsIdSiteRoute
  '/projects/$id/submittals': typeof AuthenticatedAppProjectsIdSubmittalsRoute
  '/projects/$id/team': typeof AuthenticatedAppProjectsIdTeamRoute
  '/projects/$id/transmittals': typeof AuthenticatedAppProjectsIdTransmittalsRoute
  '/api/messages/conversations/$id/members': typeof ApiMessagesConversationsIdMembersRoute
  '/projects/$id': typeof AuthenticatedAppProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/api/activity': typeof ApiActivityRoute
  '/api/bids': typeof ApiBidsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/contractors': typeof ApiContractorsRouteWithChildren
  '/api/invites': typeof ApiInvitesRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/tenders': typeof ApiTendersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/vs/5bloc-vs-fieldwire': typeof Vs5blocVsFieldwireRoute
  '/vs/5bloc-vs-procore': typeof Vs5blocVsProcoreRoute
  '/_authenticated/_app/cad': typeof AuthenticatedAppCadRoute
  '/_authenticated/_app/calendar': typeof AuthenticatedAppCalendarRoute
  '/_authenticated/_app/catalog': typeof AuthenticatedAppCatalogRoute
  '/_authenticated/_app/coordination': typeof AuthenticatedAppCoordinationRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/_app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/_app/messages': typeof AuthenticatedAppMessagesRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/contractors/$id': typeof ApiContractorsIdRoute
  '/api/contractors/architects': typeof ApiContractorsArchitectsRouteWithChildren
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRouteWithChildren
  '/api/org/studio-project': typeof ApiOrgStudioProjectRoute
  '/api/org/team': typeof ApiOrgTeamRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/tenders/$id': typeof ApiTendersIdRoute
  '/_authenticated/_app/clients/$id': typeof AuthenticatedAppClientsIdRoute
  '/_authenticated/_app/invoices/new': typeof AuthenticatedAppInvoicesNewRoute
  '/_authenticated/_app/marketplace/$id': typeof AuthenticatedAppMarketplaceIdRoute
  '/_authenticated/_app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/contractors/architects/$id': typeof ApiContractorsArchitectsIdRoute
  '/api/messages/users/search': typeof ApiMessagesUsersSearchRoute
  '/api/projects/$id/consultant-payments': typeof ApiProjectsIdConsultantPaymentsRoute
  '/api/projects/$id/document-annotations': typeof ApiProjectsIdDocumentAnnotationsRoute
  '/api/projects/$id/document-versions': typeof ApiProjectsIdDocumentVersionsRoute
  '/api/projects/$id/documents': typeof ApiProjectsIdDocumentsRoute
  '/api/projects/$id/expenses': typeof ApiProjectsIdExpensesRoute
  '/api/projects/$id/issues': typeof ApiProjectsIdIssuesRoute
  '/api/projects/$id/meetings': typeof ApiProjectsIdMeetingsRoute
  '/api/projects/$id/members': typeof ApiProjectsIdMembersRoute
  '/api/projects/$id/messages': typeof ApiProjectsIdMessagesRoute
  '/api/projects/$id/milestones': typeof ApiProjectsIdMilestonesRoute
  '/api/projects/$id/permits': typeof ApiProjectsIdPermitsRoute
  '/api/projects/$id/rfis': typeof ApiProjectsIdRfisRoute
  '/api/projects/$id/site': typeof ApiProjectsIdSiteRoute
  '/api/projects/$id/submittals': typeof ApiProjectsIdSubmittalsRoute
  '/api/projects/$id/tenders': typeof ApiProjectsIdTendersRoute
  '/api/projects/$id/transmittals': typeof ApiProjectsIdTransmittalsRoute
  '/_authenticated/_app/clients/': typeof AuthenticatedAppClientsIndexRoute
  '/_authenticated/_app/invoices/': typeof AuthenticatedAppInvoicesIndexRoute
  '/_authenticated/_app/marketplace/': typeof AuthenticatedAppMarketplaceIndexRoute
  '/_authenticated/_app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/_authenticated/_app/marketplace/architects/$id': typeof AuthenticatedAppMarketplaceArchitectsIdRoute
  '/_authenticated/_app/marketplace/tenders/$id': typeof AuthenticatedAppMarketplaceTendersIdRoute
  '/_authenticated/_app/projects/$id/documents': typeof AuthenticatedAppProjectsIdDocumentsRoute
  '/_authenticated/_app/projects/$id/invoices': typeof AuthenticatedAppProjectsIdInvoicesRoute
  '/_authenticated/_app/projects/$id/issues': typeof AuthenticatedAppProjectsIdIssuesRoute
  '/_authenticated/_app/projects/$id/meetings': typeof AuthenticatedAppProjectsIdMeetingsRoute
  '/_authenticated/_app/projects/$id/messages': typeof AuthenticatedAppProjectsIdMessagesRoute
  '/_authenticated/_app/projects/$id/permits': typeof AuthenticatedAppProjectsIdPermitsRoute
  '/_authenticated/_app/projects/$id/portal': typeof AuthenticatedAppProjectsIdPortalRoute
  '/_authenticated/_app/projects/$id/rfis': typeof AuthenticatedAppProjectsIdRfisRoute
  '/_authenticated/_app/projects/$id/settings': typeof AuthenticatedAppProjectsIdSettingsRoute
  '/_authenticated/_app/projects/$id/site': typeof AuthenticatedAppProjectsIdSiteRoute
  '/_authenticated/_app/projects/$id/submittals': typeof AuthenticatedAppProjectsIdSubmittalsRoute
  '/_authenticated/_app/projects/$id/team': typeof AuthenticatedAppProjectsIdTeamRoute
  '/_authenticated/_app/projects/$id/transmittals': typeof AuthenticatedAppProjectsIdTransmittalsRoute
  '/api/messages/conversations/$id/members': typeof ApiMessagesConversationsIdMembersRoute
  '/_authenticated/_app/projects/$id/': typeof AuthenticatedAppProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/changelog'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/api/activity'
    | '/api/bids'
    | '/api/clients'
    | '/api/contractors'
    | '/api/invites'
    | '/api/invoices'
    | '/api/me'
    | '/api/meetings'
    | '/api/notifications'
    | '/api/projects'
    | '/api/tenders'
    | '/auth/callback'
    | '/vs/5bloc-vs-fieldwire'
    | '/vs/5bloc-vs-procore'
    | '/cad'
    | '/calendar'
    | '/catalog'
    | '/coordination'
    | '/dashboard'
    | '/documents'
    | '/integrations'
    | '/messages'
    | '/settings'
    | '/api/clients/$id'
    | '/api/contractors/$id'
    | '/api/contractors/architects'
    | '/api/files/download'
    | '/api/files/upload'
    | '/api/invoices/$id'
    | '/api/messages/conversations'
    | '/api/org/studio-project'
    | '/api/org/team'
    | '/api/projects/$id'
    | '/api/tenders/$id'
    | '/clients/$id'
    | '/invoices/new'
    | '/marketplace/$id'
    | '/projects/new'
    | '/api/contractors/architects/$id'
    | '/api/messages/users/search'
    | '/api/projects/$id/consultant-payments'
    | '/api/projects/$id/document-annotations'
    | '/api/projects/$id/document-versions'
    | '/api/projects/$id/documents'
    | '/api/projects/$id/expenses'
    | '/api/projects/$id/issues'
    | '/api/projects/$id/meetings'
    | '/api/projects/$id/members'
    | '/api/projects/$id/messages'
    | '/api/projects/$id/milestones'
    | '/api/projects/$id/permits'
    | '/api/projects/$id/rfis'
    | '/api/projects/$id/site'
    | '/api/projects/$id/submittals'
    | '/api/projects/$id/tenders'
    | '/api/projects/$id/transmittals'
    | '/clients/'
    | '/invoices/'
    | '/marketplace/'
    | '/projects/'
    | '/marketplace/architects/$id'
    | '/marketplace/tenders/$id'
    | '/projects/$id/documents'
    | '/projects/$id/invoices'
    | '/projects/$id/issues'
    | '/projects/$id/meetings'
    | '/projects/$id/messages'
    | '/projects/$id/permits'
    | '/projects/$id/portal'
    | '/projects/$id/rfis'
    | '/projects/$id/settings'
    | '/projects/$id/site'
    | '/projects/$id/submittals'
    | '/projects/$id/team'
    | '/projects/$id/transmittals'
    | '/api/messages/conversations/$id/members'
    | '/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/api/activity'
    | '/api/bids'
    | '/api/clients'
    | '/api/contractors'
    | '/api/invites'
    | '/api/invoices'
    | '/api/me'
    | '/api/meetings'
    | '/api/notifications'
    | '/api/projects'
    | '/api/tenders'
    | '/auth/callback'
    | '/vs/5bloc-vs-fieldwire'
    | '/vs/5bloc-vs-procore'
    | '/cad'
    | '/calendar'
    | '/catalog'
    | '/coordination'
    | '/dashboard'
    | '/documents'
    | '/integrations'
    | '/messages'
    | '/settings'
    | '/api/clients/$id'
    | '/api/contractors/$id'
    | '/api/contractors/architects'
    | '/api/files/download'
    | '/api/files/upload'
    | '/api/invoices/$id'
    | '/api/messages/conversations'
    | '/api/org/studio-project'
    | '/api/org/team'
    | '/api/projects/$id'
    | '/api/tenders/$id'
    | '/clients/$id'
    | '/invoices/new'
    | '/marketplace/$id'
    | '/projects/new'
    | '/api/contractors/architects/$id'
    | '/api/messages/users/search'
    | '/api/projects/$id/consultant-payments'
    | '/api/projects/$id/document-annotations'
    | '/api/projects/$id/document-versions'
    | '/api/projects/$id/documents'
    | '/api/projects/$id/expenses'
    | '/api/projects/$id/issues'
    | '/api/projects/$id/meetings'
    | '/api/projects/$id/members'
    | '/api/projects/$id/messages'
    | '/api/projects/$id/milestones'
    | '/api/projects/$id/permits'
    | '/api/projects/$id/rfis'
    | '/api/projects/$id/site'
    | '/api/projects/$id/submittals'
    | '/api/projects/$id/tenders'
    | '/api/projects/$id/transmittals'
    | '/clients'
    | '/invoices'
    | '/marketplace'
    | '/projects'
    | '/marketplace/architects/$id'
    | '/marketplace/tenders/$id'
    | '/projects/$id/documents'
    | '/projects/$id/invoices'
    | '/projects/$id/issues'
    | '/projects/$id/meetings'
    | '/projects/$id/messages'
    | '/projects/$id/permits'
    | '/projects/$id/portal'
    | '/projects/$id/rfis'
    | '/projects/$id/settings'
    | '/projects/$id/site'
    | '/projects/$id/submittals'
    | '/projects/$id/team'
    | '/projects/$id/transmittals'
    | '/api/messages/conversations/$id/members'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/changelog'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_authenticated/_app'
    | '/api/activity'
    | '/api/bids'
    | '/api/clients'
    | '/api/contractors'
    | '/api/invites'
    | '/api/invoices'
    | '/api/me'
    | '/api/meetings'
    | '/api/notifications'
    | '/api/projects'
    | '/api/tenders'
    | '/auth/callback'
    | '/vs/5bloc-vs-fieldwire'
    | '/vs/5bloc-vs-procore'
    | '/_authenticated/_app/cad'
    | '/_authenticated/_app/calendar'
    | '/_authenticated/_app/catalog'
    | '/_authenticated/_app/coordination'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/documents'
    | '/_authenticated/_app/integrations'
    | '/_authenticated/_app/messages'
    | '/_authenticated/_app/settings'
    | '/api/clients/$id'
    | '/api/contractors/$id'
    | '/api/contractors/architects'
    | '/api/files/download'
    | '/api/files/upload'
    | '/api/invoices/$id'
    | '/api/messages/conversations'
    | '/api/org/studio-project'
    | '/api/org/team'
    | '/api/projects/$id'
    | '/api/tenders/$id'
    | '/_authenticated/_app/clients/$id'
    | '/_authenticated/_app/invoices/new'
    | '/_authenticated/_app/marketplace/$id'
    | '/_authenticated/_app/projects/new'
    | '/api/contractors/architects/$id'
    | '/api/messages/users/search'
    | '/api/projects/$id/consultant-payments'
    | '/api/projects/$id/document-annotations'
    | '/api/projects/$id/document-versions'
    | '/api/projects/$id/documents'
    | '/api/projects/$id/expenses'
    | '/api/projects/$id/issues'
    | '/api/projects/$id/meetings'
    | '/api/projects/$id/members'
    | '/api/projects/$id/messages'
    | '/api/projects/$id/milestones'
    | '/api/projects/$id/permits'
    | '/api/projects/$id/rfis'
    | '/api/projects/$id/site'
    | '/api/projects/$id/submittals'
    | '/api/projects/$id/tenders'
    | '/api/projects/$id/transmittals'
    | '/_authenticated/_app/clients/'
    | '/_authenticated/_app/invoices/'
    | '/_authenticated/_app/marketplace/'
    | '/_authenticated/_app/projects/'
    | '/_authenticated/_app/marketplace/architects/$id'
    | '/_authenticated/_app/marketplace/tenders/$id'
    | '/_authenticated/_app/projects/$id/documents'
    | '/_authenticated/_app/projects/$id/invoices'
    | '/_authenticated/_app/projects/$id/issues'
    | '/_authenticated/_app/projects/$id/meetings'
    | '/_authenticated/_app/projects/$id/messages'
    | '/_authenticated/_app/projects/$id/permits'
    | '/_authenticated/_app/projects/$id/portal'
    | '/_authenticated/_app/projects/$id/rfis'
    | '/_authenticated/_app/projects/$id/settings'
    | '/_authenticated/_app/projects/$id/site'
    | '/_authenticated/_app/projects/$id/submittals'
    | '/_authenticated/_app/projects/$id/team'
    | '/_authenticated/_app/projects/$id/transmittals'
    | '/api/messages/conversations/$id/members'
    | '/_authenticated/_app/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ChangelogRoute: typeof ChangelogRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiActivityRoute: typeof ApiActivityRoute
  ApiBidsRoute: typeof ApiBidsRoute
  ApiClientsRoute: typeof ApiClientsRouteWithChildren
  ApiContractorsRoute: typeof ApiContractorsRouteWithChildren
  ApiInvitesRoute: typeof ApiInvitesRoute
  ApiInvoicesRoute: typeof ApiInvoicesRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  ApiMeetingsRoute: typeof ApiMeetingsRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiTendersRoute: typeof ApiTendersRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  Vs5blocVsFieldwireRoute: typeof Vs5blocVsFieldwireRoute
  Vs5blocVsProcoreRoute: typeof Vs5blocVsProcoreRoute
  ApiFilesDownloadRoute: typeof ApiFilesDownloadRoute
  ApiFilesUploadRoute: typeof ApiFilesUploadRoute
  ApiMessagesConversationsRoute: typeof ApiMessagesConversationsRouteWithChildren
  ApiOrgStudioProjectRoute: typeof ApiOrgStudioProjectRoute
  ApiOrgTeamRoute: typeof ApiOrgTeamRoute
  ApiMessagesUsersSearchRoute: typeof ApiMessagesUsersSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bids': {
      id: '/api/bids'
      path: '/api/bids'
      fullPath: '/api/bids'
      preLoaderRoute: typeof ApiBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients': {
      id: '/api/clients'
      path: '/api/clients'
      fullPath: '/api/clients'
      preLoaderRoute: typeof ApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contractors': {
      id: '/api/contractors'
      path: '/api/contractors'
      fullPath: '/api/contractors'
      preLoaderRoute: typeof ApiContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invites': {
      id: '/api/invites'
      path: '/api/invites'
      fullPath: '/api/invites'
      preLoaderRoute: typeof ApiInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices': {
      id: '/api/invoices'
      path: '/api/invoices'
      fullPath: '/api/invoices'
      preLoaderRoute: typeof ApiInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings': {
      id: '/api/meetings'
      path: '/api/meetings'
      fullPath: '/api/meetings'
      preLoaderRoute: typeof ApiMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenders': {
      id: '/api/tenders'
      path: '/api/tenders'
      fullPath: '/api/tenders'
      preLoaderRoute: typeof ApiTendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/5bloc-vs-fieldwire': {
      id: '/vs/5bloc-vs-fieldwire'
      path: '/vs/5bloc-vs-fieldwire'
      fullPath: '/vs/5bloc-vs-fieldwire'
      preLoaderRoute: typeof Vs5blocVsFieldwireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/5bloc-vs-procore': {
      id: '/vs/5bloc-vs-procore'
      path: '/vs/5bloc-vs-procore'
      fullPath: '/vs/5bloc-vs-procore'
      preLoaderRoute: typeof Vs5blocVsProcoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/cad': {
      id: '/_authenticated/_app/cad'
      path: '/cad'
      fullPath: '/cad'
      preLoaderRoute: typeof AuthenticatedAppCadRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/calendar': {
      id: '/_authenticated/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedAppCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/catalog': {
      id: '/_authenticated/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedAppCatalogRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/coordination': {
      id: '/_authenticated/_app/coordination'
      path: '/coordination'
      fullPath: '/coordination'
      preLoaderRoute: typeof AuthenticatedAppCoordinationRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/documents': {
      id: '/_authenticated/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/integrations': {
      id: '/_authenticated/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/messages': {
      id: '/_authenticated/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/clients/$id': {
      id: '/api/clients/$id'
      path: '/$id'
      fullPath: '/api/clients/$id'
      preLoaderRoute: typeof ApiClientsIdRouteImport
      parentRoute: typeof ApiClientsRoute
    }
    '/api/contractors/$id': {
      id: '/api/contractors/$id'
      path: '/$id'
      fullPath: '/api/contractors/$id'
      preLoaderRoute: typeof ApiContractorsIdRouteImport
      parentRoute: typeof ApiContractorsRoute
    }
    '/api/contractors/architects': {
      id: '/api/contractors/architects'
      path: '/architects'
      fullPath: '/api/contractors/architects'
      preLoaderRoute: typeof ApiContractorsArchitectsRouteImport
      parentRoute: typeof ApiContractorsRoute
    }
    '/api/files/download': {
      id: '/api/files/download'
      path: '/api/files/download'
      fullPath: '/api/files/download'
      preLoaderRoute: typeof ApiFilesDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/upload': {
      id: '/api/files/upload'
      path: '/api/files/upload'
      fullPath: '/api/files/upload'
      preLoaderRoute: typeof ApiFilesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices/$id': {
      id: '/api/invoices/$id'
      path: '/$id'
      fullPath: '/api/invoices/$id'
      preLoaderRoute: typeof ApiInvoicesIdRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/messages/conversations': {
      id: '/api/messages/conversations'
      path: '/api/messages/conversations'
      fullPath: '/api/messages/conversations'
      preLoaderRoute: typeof ApiMessagesConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/studio-project': {
      id: '/api/org/studio-project'
      path: '/api/org/studio-project'
      fullPath: '/api/org/studio-project'
      preLoaderRoute: typeof ApiOrgStudioProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/team': {
      id: '/api/org/team'
      path: '/api/org/team'
      fullPath: '/api/org/team'
      preLoaderRoute: typeof ApiOrgTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/tenders/$id': {
      id: '/api/tenders/$id'
      path: '/$id'
      fullPath: '/api/tenders/$id'
      preLoaderRoute: typeof ApiTendersIdRouteImport
      parentRoute: typeof ApiTendersRoute
    }
    '/_authenticated/_app/clients/': {
      id: '/_authenticated/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedAppClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/clients/$id': {
      id: '/_authenticated/_app/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedAppClientsIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/invoices/': {
      id: '/_authenticated/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedAppInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/invoices/new': {
      id: '/_authenticated/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedAppInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/marketplace/': {
      id: '/_authenticated/_app/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/marketplace/$id': {
      id: '/_authenticated/_app/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/': {
      id: '/_authenticated/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/new': {
      id: '/_authenticated/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedAppProjectsNewRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/contractors/architects/$id': {
      id: '/api/contractors/architects/$id'
      path: '/$id'
      fullPath: '/api/contractors/architects/$id'
      preLoaderRoute: typeof ApiContractorsArchitectsIdRouteImport
      parentRoute: typeof ApiContractorsArchitectsRoute
    }
    '/api/messages/users/search': {
      id: '/api/messages/users/search'
      path: '/api/messages/users/search'
      fullPath: '/api/messages/users/search'
      preLoaderRoute: typeof ApiMessagesUsersSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/consultant-payments': {
      id: '/api/projects/$id/consultant-payments'
      path: '/consultant-payments'
      fullPath: '/api/projects/$id/consultant-payments'
      preLoaderRoute: typeof ApiProjectsIdConsultantPaymentsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/document-annotations': {
      id: '/api/projects/$id/document-annotations'
      path: '/document-annotations'
      fullPath: '/api/projects/$id/document-annotations'
      preLoaderRoute: typeof ApiProjectsIdDocumentAnnotationsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/document-versions': {
      id: '/api/projects/$id/document-versions'
      path: '/document-versions'
      fullPath: '/api/projects/$id/document-versions'
      preLoaderRoute: typeof ApiProjectsIdDocumentVersionsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/documents': {
      id: '/api/projects/$id/documents'
      path: '/documents'
      fullPath: '/api/projects/$id/documents'
      preLoaderRoute: typeof ApiProjectsIdDocumentsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/expenses': {
      id: '/api/projects/$id/expenses'
      path: '/expenses'
      fullPath: '/api/projects/$id/expenses'
      preLoaderRoute: typeof ApiProjectsIdExpensesRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/issues': {
      id: '/api/projects/$id/issues'
      path: '/issues'
      fullPath: '/api/projects/$id/issues'
      preLoaderRoute: typeof ApiProjectsIdIssuesRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/meetings': {
      id: '/api/projects/$id/meetings'
      path: '/meetings'
      fullPath: '/api/projects/$id/meetings'
      preLoaderRoute: typeof ApiProjectsIdMeetingsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/members': {
      id: '/api/projects/$id/members'
      path: '/members'
      fullPath: '/api/projects/$id/members'
      preLoaderRoute: typeof ApiProjectsIdMembersRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/messages': {
      id: '/api/projects/$id/messages'
      path: '/messages'
      fullPath: '/api/projects/$id/messages'
      preLoaderRoute: typeof ApiProjectsIdMessagesRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/milestones': {
      id: '/api/projects/$id/milestones'
      path: '/milestones'
      fullPath: '/api/projects/$id/milestones'
      preLoaderRoute: typeof ApiProjectsIdMilestonesRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/permits': {
      id: '/api/projects/$id/permits'
      path: '/permits'
      fullPath: '/api/projects/$id/permits'
      preLoaderRoute: typeof ApiProjectsIdPermitsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/rfis': {
      id: '/api/projects/$id/rfis'
      path: '/rfis'
      fullPath: '/api/projects/$id/rfis'
      preLoaderRoute: typeof ApiProjectsIdRfisRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/site': {
      id: '/api/projects/$id/site'
      path: '/site'
      fullPath: '/api/projects/$id/site'
      preLoaderRoute: typeof ApiProjectsIdSiteRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/submittals': {
      id: '/api/projects/$id/submittals'
      path: '/submittals'
      fullPath: '/api/projects/$id/submittals'
      preLoaderRoute: typeof ApiProjectsIdSubmittalsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/tenders': {
      id: '/api/projects/$id/tenders'
      path: '/tenders'
      fullPath: '/api/projects/$id/tenders'
      preLoaderRoute: typeof ApiProjectsIdTendersRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/transmittals': {
      id: '/api/projects/$id/transmittals'
      path: '/transmittals'
      fullPath: '/api/projects/$id/transmittals'
      preLoaderRoute: typeof ApiProjectsIdTransmittalsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/_authenticated/_app/marketplace/architects/$id': {
      id: '/_authenticated/_app/marketplace/architects/$id'
      path: '/marketplace/architects/$id'
      fullPath: '/marketplace/architects/$id'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceArchitectsIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/marketplace/tenders/$id': {
      id: '/_authenticated/_app/marketplace/tenders/$id'
      path: '/marketplace/tenders/$id'
      fullPath: '/marketplace/tenders/$id'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceTendersIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/': {
      id: '/_authenticated/_app/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/documents': {
      id: '/_authenticated/_app/projects/$id/documents'
      path: '/projects/$id/documents'
      fullPath: '/projects/$id/documents'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/invoices': {
      id: '/_authenticated/_app/projects/$id/invoices'
      path: '/projects/$id/invoices'
      fullPath: '/projects/$id/invoices'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/issues': {
      id: '/_authenticated/_app/projects/$id/issues'
      path: '/projects/$id/issues'
      fullPath: '/projects/$id/issues'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdIssuesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/meetings': {
      id: '/_authenticated/_app/projects/$id/meetings'
      path: '/projects/$id/meetings'
      fullPath: '/projects/$id/meetings'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdMeetingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/messages': {
      id: '/_authenticated/_app/projects/$id/messages'
      path: '/projects/$id/messages'
      fullPath: '/projects/$id/messages'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdMessagesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/permits': {
      id: '/_authenticated/_app/projects/$id/permits'
      path: '/projects/$id/permits'
      fullPath: '/projects/$id/permits'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdPermitsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/portal': {
      id: '/_authenticated/_app/projects/$id/portal'
      path: '/projects/$id/portal'
      fullPath: '/projects/$id/portal'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdPortalRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/rfis': {
      id: '/_authenticated/_app/projects/$id/rfis'
      path: '/projects/$id/rfis'
      fullPath: '/projects/$id/rfis'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdRfisRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/settings': {
      id: '/_authenticated/_app/projects/$id/settings'
      path: '/projects/$id/settings'
      fullPath: '/projects/$id/settings'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/site': {
      id: '/_authenticated/_app/projects/$id/site'
      path: '/projects/$id/site'
      fullPath: '/projects/$id/site'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdSiteRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/submittals': {
      id: '/_authenticated/_app/projects/$id/submittals'
      path: '/projects/$id/submittals'
      fullPath: '/projects/$id/submittals'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdSubmittalsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/team': {
      id: '/_authenticated/_app/projects/$id/team'
      path: '/projects/$id/team'
      fullPath: '/projects/$id/team'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdTeamRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects/$id/transmittals': {
      id: '/_authenticated/_app/projects/$id/transmittals'
      path: '/projects/$id/transmittals'
      fullPath: '/projects/$id/transmittals'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdTransmittalsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/messages/conversations/$id/members': {
      id: '/api/messages/conversations/$id/members'
      path: '/$id/members'
      fullPath: '/api/messages/conversations/$id/members'
      preLoaderRoute: typeof ApiMessagesConversationsIdMembersRouteImport
      parentRoute: typeof ApiMessagesConversationsRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppCadRoute: typeof AuthenticatedAppCadRoute
  AuthenticatedAppCalendarRoute: typeof AuthenticatedAppCalendarRoute
  AuthenticatedAppCatalogRoute: typeof AuthenticatedAppCatalogRoute
  AuthenticatedAppCoordinationRoute: typeof AuthenticatedAppCoordinationRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppClientsIdRoute: typeof AuthenticatedAppClientsIdRoute
  AuthenticatedAppInvoicesNewRoute: typeof AuthenticatedAppInvoicesNewRoute
  AuthenticatedAppMarketplaceIdRoute: typeof AuthenticatedAppMarketplaceIdRoute
  AuthenticatedAppProjectsNewRoute: typeof AuthenticatedAppProjectsNewRoute
  AuthenticatedAppClientsIndexRoute: typeof AuthenticatedAppClientsIndexRoute
  AuthenticatedAppInvoicesIndexRoute: typeof AuthenticatedAppInvoicesIndexRoute
  AuthenticatedAppMarketplaceIndexRoute: typeof AuthenticatedAppMarketplaceIndexRoute
  AuthenticatedAppProjectsIndexRoute: typeof AuthenticatedAppProjectsIndexRoute
  AuthenticatedAppMarketplaceArchitectsIdRoute: typeof AuthenticatedAppMarketplaceArchitectsIdRoute
  AuthenticatedAppMarketplaceTendersIdRoute: typeof AuthenticatedAppMarketplaceTendersIdRoute
  AuthenticatedAppProjectsIdDocumentsRoute: typeof AuthenticatedAppProjectsIdDocumentsRoute
  AuthenticatedAppProjectsIdInvoicesRoute: typeof AuthenticatedAppProjectsIdInvoicesRoute
  AuthenticatedAppProjectsIdIssuesRoute: typeof AuthenticatedAppProjectsIdIssuesRoute
  AuthenticatedAppProjectsIdMeetingsRoute: typeof AuthenticatedAppProjectsIdMeetingsRoute
  AuthenticatedAppProjectsIdMessagesRoute: typeof AuthenticatedAppProjectsIdMessagesRoute
  AuthenticatedAppProjectsIdPermitsRoute: typeof AuthenticatedAppProjectsIdPermitsRoute
  AuthenticatedAppProjectsIdPortalRoute: typeof AuthenticatedAppProjectsIdPortalRoute
  AuthenticatedAppProjectsIdRfisRoute: typeof AuthenticatedAppProjectsIdRfisRoute
  AuthenticatedAppProjectsIdSettingsRoute: typeof AuthenticatedAppProjectsIdSettingsRoute
  AuthenticatedAppProjectsIdSiteRoute: typeof AuthenticatedAppProjectsIdSiteRoute
  AuthenticatedAppProjectsIdSubmittalsRoute: typeof AuthenticatedAppProjectsIdSubmittalsRoute
  AuthenticatedAppProjectsIdTeamRoute: typeof AuthenticatedAppProjectsIdTeamRoute
  AuthenticatedAppProjectsIdTransmittalsRoute: typeof AuthenticatedAppProjectsIdTransmittalsRoute
  AuthenticatedAppProjectsIdIndexRoute: typeof AuthenticatedAppProjectsIdIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppCadRoute: AuthenticatedAppCadRoute,
  AuthenticatedAppCalendarRoute: AuthenticatedAppCalendarRoute,
  AuthenticatedAppCatalogRoute: AuthenticatedAppCatalogRoute,
  AuthenticatedAppCoordinationRoute: AuthenticatedAppCoordinationRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppClientsIdRoute: AuthenticatedAppClientsIdRoute,
  AuthenticatedAppInvoicesNewRoute: AuthenticatedAppInvoicesNewRoute,
  AuthenticatedAppMarketplaceIdRoute: AuthenticatedAppMarketplaceIdRoute,
  AuthenticatedAppProjectsNewRoute: AuthenticatedAppProjectsNewRoute,
  AuthenticatedAppClientsIndexRoute: AuthenticatedAppClientsIndexRoute,
  AuthenticatedAppInvoicesIndexRoute: AuthenticatedAppInvoicesIndexRoute,
  AuthenticatedAppMarketplaceIndexRoute: AuthenticatedAppMarketplaceIndexRoute,
  AuthenticatedAppProjectsIndexRoute: AuthenticatedAppProjectsIndexRoute,
  AuthenticatedAppMarketplaceArchitectsIdRoute:
    AuthenticatedAppMarketplaceArchitectsIdRoute,
  AuthenticatedAppMarketplaceTendersIdRoute:
    AuthenticatedAppMarketplaceTendersIdRoute,
  AuthenticatedAppProjectsIdDocumentsRoute:
    AuthenticatedAppProjectsIdDocumentsRoute,
  AuthenticatedAppProjectsIdInvoicesRoute:
    AuthenticatedAppProjectsIdInvoicesRoute,
  AuthenticatedAppProjectsIdIssuesRoute: AuthenticatedAppProjectsIdIssuesRoute,
  AuthenticatedAppProjectsIdMeetingsRoute:
    AuthenticatedAppProjectsIdMeetingsRoute,
  AuthenticatedAppProjectsIdMessagesRoute:
    AuthenticatedAppProjectsIdMessagesRoute,
  AuthenticatedAppProjectsIdPermitsRoute:
    AuthenticatedAppProjectsIdPermitsRoute,
  AuthenticatedAppProjectsIdPortalRoute: AuthenticatedAppProjectsIdPortalRoute,
  AuthenticatedAppProjectsIdRfisRoute: AuthenticatedAppProjectsIdRfisRoute,
  AuthenticatedAppProjectsIdSettingsRoute:
    AuthenticatedAppProjectsIdSettingsRoute,
  AuthenticatedAppProjectsIdSiteRoute: AuthenticatedAppProjectsIdSiteRoute,
  AuthenticatedAppProjectsIdSubmittalsRoute:
    AuthenticatedAppProjectsIdSubmittalsRoute,
  AuthenticatedAppProjectsIdTeamRoute: AuthenticatedAppProjectsIdTeamRoute,
  AuthenticatedAppProjectsIdTransmittalsRoute:
    AuthenticatedAppProjectsIdTransmittalsRoute,
  AuthenticatedAppProjectsIdIndexRoute: AuthenticatedAppProjectsIdIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiClientsRouteChildren {
  ApiClientsIdRoute: typeof ApiClientsIdRoute
}

const ApiClientsRouteChildren: ApiClientsRouteChildren = {
  ApiClientsIdRoute: ApiClientsIdRoute,
}

const ApiClientsRouteWithChildren = ApiClientsRoute._addFileChildren(
  ApiClientsRouteChildren,
)

interface ApiContractorsArchitectsRouteChildren {
  ApiContractorsArchitectsIdRoute: typeof ApiContractorsArchitectsIdRoute
}

const ApiContractorsArchitectsRouteChildren: ApiContractorsArchitectsRouteChildren =
  {
    ApiContractorsArchitectsIdRoute: ApiContractorsArchitectsIdRoute,
  }

const ApiContractorsArchitectsRouteWithChildren =
  ApiContractorsArchitectsRoute._addFileChildren(
    ApiContractorsArchitectsRouteChildren,
  )

interface ApiContractorsRouteChildren {
  ApiContractorsIdRoute: typeof ApiContractorsIdRoute
  ApiContractorsArchitectsRoute: typeof ApiContractorsArchitectsRouteWithChildren
}

const ApiContractorsRouteChildren: ApiContractorsRouteChildren = {
  ApiContractorsIdRoute: ApiContractorsIdRoute,
  ApiContractorsArchitectsRoute: ApiContractorsArchitectsRouteWithChildren,
}

const ApiContractorsRouteWithChildren = ApiContractorsRoute._addFileChildren(
  ApiContractorsRouteChildren,
)

interface ApiInvoicesRouteChildren {
  ApiInvoicesIdRoute: typeof ApiInvoicesIdRoute
}

const ApiInvoicesRouteChildren: ApiInvoicesRouteChildren = {
  ApiInvoicesIdRoute: ApiInvoicesIdRoute,
}

const ApiInvoicesRouteWithChildren = ApiInvoicesRoute._addFileChildren(
  ApiInvoicesRouteChildren,
)

interface ApiProjectsIdRouteChildren {
  ApiProjectsIdConsultantPaymentsRoute: typeof ApiProjectsIdConsultantPaymentsRoute
  ApiProjectsIdDocumentAnnotationsRoute: typeof ApiProjectsIdDocumentAnnotationsRoute
  ApiProjectsIdDocumentVersionsRoute: typeof ApiProjectsIdDocumentVersionsRoute
  ApiProjectsIdDocumentsRoute: typeof ApiProjectsIdDocumentsRoute
  ApiProjectsIdExpensesRoute: typeof ApiProjectsIdExpensesRoute
  ApiProjectsIdIssuesRoute: typeof ApiProjectsIdIssuesRoute
  ApiProjectsIdMeetingsRoute: typeof ApiProjectsIdMeetingsRoute
  ApiProjectsIdMembersRoute: typeof ApiProjectsIdMembersRoute
  ApiProjectsIdMessagesRoute: typeof ApiProjectsIdMessagesRoute
  ApiProjectsIdMilestonesRoute: typeof ApiProjectsIdMilestonesRoute
  ApiProjectsIdPermitsRoute: typeof ApiProjectsIdPermitsRoute
  ApiProjectsIdRfisRoute: typeof ApiProjectsIdRfisRoute
  ApiProjectsIdSiteRoute: typeof ApiProjectsIdSiteRoute
  ApiProjectsIdSubmittalsRoute: typeof ApiProjectsIdSubmittalsRoute
  ApiProjectsIdTendersRoute: typeof ApiProjectsIdTendersRoute
  ApiProjectsIdTransmittalsRoute: typeof ApiProjectsIdTransmittalsRoute
}

const ApiProjectsIdRouteChildren: ApiProjectsIdRouteChildren = {
  ApiProjectsIdConsultantPaymentsRoute: ApiProjectsIdConsultantPaymentsRoute,
  ApiProjectsIdDocumentAnnotationsRoute: ApiProjectsIdDocumentAnnotationsRoute,
  ApiProjectsIdDocumentVersionsRoute: ApiProjectsIdDocumentVersionsRoute,
  ApiProjectsIdDocumentsRoute: ApiProjectsIdDocumentsRoute,
  ApiProjectsIdExpensesRoute: ApiProjectsIdExpensesRoute,
  ApiProjectsIdIssuesRoute: ApiProjectsIdIssuesRoute,
  ApiProjectsIdMeetingsRoute: ApiProjectsIdMeetingsRoute,
  ApiProjectsIdMembersRoute: ApiProjectsIdMembersRoute,
  ApiProjectsIdMessagesRoute: ApiProjectsIdMessagesRoute,
  ApiProjectsIdMilestonesRoute: ApiProjectsIdMilestonesRoute,
  ApiProjectsIdPermitsRoute: ApiProjectsIdPermitsRoute,
  ApiProjectsIdRfisRoute: ApiProjectsIdRfisRoute,
  ApiProjectsIdSiteRoute: ApiProjectsIdSiteRoute,
  ApiProjectsIdSubmittalsRoute: ApiProjectsIdSubmittalsRoute,
  ApiProjectsIdTendersRoute: ApiProjectsIdTendersRoute,
  ApiProjectsIdTransmittalsRoute: ApiProjectsIdTransmittalsRoute,
}

const ApiProjectsIdRouteWithChildren = ApiProjectsIdRoute._addFileChildren(
  ApiProjectsIdRouteChildren,
)

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRouteWithChildren
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRouteWithChildren,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

interface ApiTendersRouteChildren {
  ApiTendersIdRoute: typeof ApiTendersIdRoute
}

const ApiTendersRouteChildren: ApiTendersRouteChildren = {
  ApiTendersIdRoute: ApiTendersIdRoute,
}

const ApiTendersRouteWithChildren = ApiTendersRoute._addFileChildren(
  ApiTendersRouteChildren,
)

interface ApiMessagesConversationsRouteChildren {
  ApiMessagesConversationsIdMembersRoute: typeof ApiMessagesConversationsIdMembersRoute
}

const ApiMessagesConversationsRouteChildren: ApiMessagesConversationsRouteChildren =
  {
    ApiMessagesConversationsIdMembersRoute:
      ApiMessagesConversationsIdMembersRoute,
  }

const ApiMessagesConversationsRouteWithChildren =
  ApiMessagesConversationsRoute._addFileChildren(
    ApiMessagesConversationsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiActivityRoute: ApiActivityRoute,
  ApiBidsRoute: ApiBidsRoute,
  ApiClientsRoute: ApiClientsRouteWithChildren,
  ApiContractorsRoute: ApiContractorsRouteWithChildren,
  ApiInvitesRoute: ApiInvitesRoute,
  ApiInvoicesRoute: ApiInvoicesRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  ApiMeetingsRoute: ApiMeetingsRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiTendersRoute: ApiTendersRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  Vs5blocVsFieldwireRoute: Vs5blocVsFieldwireRoute,
  Vs5blocVsProcoreRoute: Vs5blocVsProcoreRoute,
  ApiFilesDownloadRoute: ApiFilesDownloadRoute,
  ApiFilesUploadRoute: ApiFilesUploadRoute,
  ApiMessagesConversationsRoute: ApiMessagesConversationsRouteWithChildren,
  ApiOrgStudioProjectRoute: ApiOrgStudioProjectRoute,
  ApiOrgTeamRoute: ApiOrgTeamRoute,
  ApiMessagesUsersSearchRoute: ApiMessagesUsersSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
